---
- name: Comprehensive security audit
  hosts: "{{ target_host }}"
  gather_facts: false
  vars:
    remote_dir: 'C:\Windows\Temp'

  tasks:
    - name: Copy SecurityAudit.ps1
      ansible.windows.win_copy:
        src: "{{ scripts_dir }}/SecurityAudit.ps1"
        dest: "{{ remote_dir }}\\SecurityAudit.ps1"

    - name: Run SecurityAudit.ps1
      ansible.windows.win_shell: "& '{{ remote_dir }}\\SecurityAudit.ps1'"
      register: result
      changed_when: false
      failed_when: false
