---
- name: Stop EBS application on "{{ tgt_env }}"
  hosts: "{{domain}}-{{tgt_env}}-OFA-APP"
  remote_user: applmgr
  gather_facts: no

  vars: 
    date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"

  vars_files:
    - vars/{{ domain }}/{{ tgt_env }}/targetdbinfo.yaml

  tasks:
    - name: Create {{ tgt_dir }} directory
      file: path={{ tgt_dir }} state=directory
# Set Suffix
    - set_fact:
        suffix: "ansible{{ 1000 | random }}"
      run_once: yes

# Set-up
# Coping script to server
    - name: Copy ebs  script to target database server
      template: src=templates/restart{{ ebs_version }}.sh.j2 dest={{ tgt_dir }}/restart.sh mode=0777

# Run Stop  command
    - name: Stop Ebs application - "{{ tgt_env }}""
      shell: '{{ tgt_dir }}/restart.sh STOP {{ tgt_apps_pwd }} {{ tgt_wblg_pswd }}'
      args:
        chdir: "{{ tgt_dir }}"
      register: fail_me
      failed_when: "fail_me.rc != 0 and fail_me.rc != 369"
      when: ebs_version == 122

    - name: Stop Ebs application - "{{ tgt_env }}""
      shell: '{{ tgt_dir }}/restart.sh STOP {{ tgt_apps_pwd }}'
      args:
        chdir: "{{ tgt_dir }}"
      register: fail_me
      failed_when: "fail_me.rc != 0 and fail_me.rc != 369"
      when: ebs_version == 121

    - debug: msg={{ fail_me.stdout_lines }}

